### ISSUE TITLE
Target Journal

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_discontent#7]
[Jennings et al. (2017)](https://academic.oup.com/poq/article/81/3/748/3858932) was published in _POQ_.  Is that a good target for this piece?  If so, what do we need to do to meet the journal's requirements.  If not, where should we take this?

**Comment by haofengma** [comment]
I like the idea of POQ. They didn't provide acceptance time and rate, but just from the perspective of theme, I think POQ is a good fit.

**Comment by Jeongho-Choi** [comment]
I like POQ. According to their website, the review process usually takes three months, which sounds like a reasonable length of time to me. And, the maximum word count is 6,500 words of text and notes, excluding figures, tables, references, and appendices. So, I think we are good to go on this.

**Comment by fsolt** [comment]
_POQ_ (used to?) have a requirement on following AAPOR guidelines on describing all survey datasets used, including the _n_, the sampling methods, and I don't know what else—which would be a nightmare for us.  I don't see that now in the [Author Guidelines](https://academic.oup.com/poq/pages/general_instructions), so that's good.  Still, I think submitting there would require as a bare minimum that we include the citations of all of the surveys we use, as @sammo3182 and I did in https://github.com/fsolt/dcpo_macrointerest/blob/main/paper/dcpo_macrointerest.pdf but we have been spotty on across projects, so adding that code and insuring all the citations needed are pasted into https://github.com/fsolt/DCPOtools/blob/master/data/surveys_data.csv would have to be added to our list of issues.  Since we're in a hurry to get this out, I'll wait for consensus on _POQ_ before assigning that work.  Your thoughts, @Tyhcass  @sammo3182 ?

**Comment by sammo3182** [comment]
Hi all, sorry for the late reply! On trip all the time…POQ still require AAPOR guidelines, Fred, but after the acceptance. And yea, that’ll be a nightmare…

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Frederick Solt ***@***.***>
发送时间: Thursday, June 27, 2024 3:54:29 AM
收件人: fsolt/dcpo_discontent ***@***.***>
抄送: Yue Hu ***@***.***>; Mention ***@***.***>
主题: Re: [fsolt/dcpo_discontent] Target Journal (Issue #7)


POQ (used to?) have a about following AAPOR guidelines on describing all survey datasets used, including the n, the sampling methods, and I don't know what else―which would be a nightmare for us. I don't see that now in the Author Guidelines<https://academic.oup.com/poq/pages/general_instructions>, so that's good. Still, I think submitting there would require as a bare minimum that we include the citations of all of the surveys we use, as @sammo3182<https://github.com/sammo3182> and I did in https://github.com/fsolt/dcpo_macrointerest/blob/main/paper/dcpo_macrointerest.pdf but we have been spotty on across projects, so adding that code and insuring all the citations needed are pasted into https://github.com/fsolt/DCPOtools/blob/master/data/surveys_data.csv would have to be added to our list of issues. Since we're in a hurry to get this out, I'll wait for consensus on POQ before assigning that work. Your thoughts, @Tyhcass<https://github.com/Tyhcass> @sammo3182<https://github.com/sammo3182> ?

―

**Comment by casstai** [comment]
I am fine with POQ. Let's consider "the nightmare" after it has been accepted.

**Comment by fsolt** [comment]
> Let's consider "the nightmare" after it has been accepted.

Oof.  Right.  If it was okay for Jennings et al. (2017), it should be okay for us, I guess.
